language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - make test
deploy:
  provider: netlify
  site: <site>
  auth: <encrypted auth>
  edge: true
on:
  branch: master
